/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Generation": "代数",
    "Hard Reset": "硬重置",
    "Max All Buildings (M": "最大所有建筑物（M",
    "Max All Buildings and X (M": "最大所有建筑物和 X (M",
    "Options": "选项",
    "Production is doubled": "产量翻倍",
    "Quadratic Automator: Reset at": "二次方自动器：重置于",
    "Quadratic Upgrades": "二次方升级",
    "randomtuba - For creating the game and setting up the GitHub link": "randomtuba - 用于创建游戏和设置 GitHub 链接",
    "root essence.": "根精华。",
    "Sacrifice": "牺牲",
    "Square Root": "平方根",
    "Thanks to these people, Algebraic Progression is the way it is.": "感谢这些人，代数级数就是这样。",
    "Unlock Functions": "解锁功能",
    "unpingabot - For helping to fix some bugs (I think": "unpingabot - 帮助修复一些错误（我认为",
    "Upgrades": "升级",
    "Why does the news ticker line break news messages?": "为什么新闻代码行会中断新闻消息？",
    "You have sacrificed": "你牺牲了",
    "Coordinate Plane": "坐标平面",
    "Cosmic47 - For making sure that the game is the best it can be": "Cosmic47 - 确保游戏是最好的",
    "gapples2 - For doing a lot of the work for AP, such as autobuyers, coordinate plane, dark theme, functions, and more": "gapples2 - 用于为 AP 完成大量工作，例如自动购买、坐标平面、深色主题、功能等",
    "Get 1x.": "获得 1 倍。",
    "Get a point factory.": "获得点工厂。",
    "Get a point portal.": "获得一个点门户。",
    "Get an autoclicker.": "获取自动点击器。",
    "Get g(x) to 1.": "使 g(x) 为 1。",
    "Get g(x) to 50.": "将 g(x) 设为 50。",
    "Get h(x) to 1.": "将 h(x) 设为 1。",
    "Get over 9000x.": "获得超过 9000 倍。",
    "Get the first row of quadratic upgrades.": "获得第一行二次升级。",
    "Get the second row of quadratic upgrades.": "获得第二排二次升级。",
    "Get the third row of quadratic upgrades.": "获得第三排二次升级。",
    "Getting Squared": "平方",
    "Go quadratic": "进二次方",
    "Inverse Quadratic": "逆二次",
    "IT'S OVER 9000": "超过9000",
    "Magic?": "魔法？",
    "Reach 10 root essence.": "达到10根精华。",
    "Reach 1e500 points.": "达到 1e500 点。",
    "Reach 50y.": "达到50岁。",
    "Sacrifice x and y.": "牺牲 x 和 y。",
    "Sacrifices to randomtuba": "对 randomtuba 的牺牲",
    "softcapped": "软上限",
    "softcapped) 2: Electric Boogaloo": "软上限) 2: 电动布加洛",
    "The End": "结束",
    "Tripler": "三倍体",
    "Unlock auto quadratic.": "解锁自动二次方。",
    "Unlock functions.": "解锁功能。",
    "Unlock Square Root.": "解锁平方根。",
    "Uprooted": "连根拔起",
    "A few upgrades later": "之后进行了几次升级",
    "A new feature?": "新功能？",
    "Actually Automation": "实际上自动化",
    "Algebra Class": "代数课",
    "Algebraic Progression": "代数级数",
    "Antimatter Dimensions (Hevipelle) - For news ticker code": "反物质维度 (Hevipelle) - 用于新闻股票代码",
    "Auto Quadratic": "自动二次",
    "Automation": "自动化",
    "Boo, DEMEMZEA, and Jayman - For testing the game": "Boo、DEMEMZEA 和 Jayman - 用于测试游戏",
    "But Y?": "但是Y?",
    "Cheater": "骗子",
    "Cost scaling is 1.1x": "成本扩展为 1.1 倍",
    "Credits": "学分",
    "Divide x cost by 2": "将 x 成本除以 2",
    "Doubler": "倍增器",
    "Due to a mathematical error in your formula, points are softcapped beyond 1e500": "由于您的公式中存在数学错误，点被软封顶超过 1e500",
    "Enter the E": "输入 E",
    "Factory Incremental": "工厂增量",
    "..for now.": "..目前。",
    "'If AP doesn't have triple exponential growth, I'm calling the police' -a human(?), 2021": "“如果 AP 没有三倍指数增长，我就报警了”——人类（？），2021",
    "If you're wondering about new content, there is going to be a 2nd prestige layer eventually added into this game.": "如果您想了解新内容，最终将在此游戏中添加第二个声望层。",
    "Gain x for {{format(xCost())}} points (X": "增益 x 花费 {{format(xCost())}} 点数 (X",
    "Gain y for {{format(yCost(),yCost().lt(1e9)?0:2)}}x (Y": "增益 y 花费 {{format(yCost(),yCost().lt(1e9)?0:2)}}x (Y",
    "X Autobuyer: {{player.autobuyers[1]?'ON':'OFF'}}": "X 自动购买者: {{player.autobuyers[1]?'打开':'关闭'}}",
    "Y Autobuyer: {{player.autobuyers[3]?'ON':'OFF'}}": "Y 自动购买者: {{player.autobuyers[3]?'打开':'关闭'}}",
    "Buy for {{format(costfunc(i))}} points{{hasQuadUpg(5)?' ('+(i+3)+')':''}}": "购买花费 {{format(costfunc(i))}} 点数{{hasQuadUpg(5)?' ('+(i+3)+')':''}}",
    "Max All Buildings, X and Y (M": "最大所有建筑物，X 和 Y（M",
    "when tuba doesn't update his game :flushed": "当 tuba 不更新他的游戏时：flushed",
    "Multiply production by 20.": "将产量乘以 20。",
    "Point Factories are stronger based on total buildings bought (hardcapped at 1e10).": "点数工厂基于购买的总建筑数更强（硬上限为 1e10）。",
    "Quadratic": "二次方",
    "Square f(x).": "平方 f(x)。",
    "Autoclickers are stronger based on total buildings bought (hardcapped at 1e10).": "根据购买的建筑总数（硬上限为 1e10），自动点击器更强大。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Everyone talks about pi, but no one talks about tau :saddening": "每个人都在谈论 pi，但没有人谈论 tau :saddening",
    "Fun Fact: A main GitHub page for Tuba's incremental games is in the works!": "有趣的事实：Tuba 增量游戏的主要 GitHub 页面正在开发中！",
    "Hey all, Scott here! My thoughts are being broadcasted on a news ticker now! No reason, just felt like it.": "大家好，斯科特在这里！ 我的想法现在正在新闻收报机上播出！ 没有理由，就是觉得。",
    "i am a news ticker, fear me": "我是新闻播报员，害怕我",
    "The action of adding news tickers is like drugs. It's pleasure, but you can't do too much of it.": "添加新闻代码的行为就像毒品一样。 这是一种乐趣，但你不能做太多。",
    "Therapist: 'Z isn't real, it can't hurt you' Z": "治疗师：“Z 不是真的，它不会伤害你”Z",
    "When your game inflates so hard your numbers reach the Small Dropping Ordinal :sus": "当您的游戏膨胀得如此之大时，您的数字达到了 小下降序数 :sus",
    "Say it with me: X, Y, Z, W, A, B, C...": "跟我说：X、Y、Z、W、A、B、C...",
    "Unreal Engine should be renamed to Imaginary Engine": "虚幻引擎应该重命名为虚幻引擎",
    "Want another game to play while you're idling? Check out Tuba's Tree! Game Link: https://randomtuba.github.io/Tubas-Tree/": "想在空闲时玩其他游戏吗？看看大号的树！游戏链接：https://randomtuba.github.io/Tubas-Tree/",
    "Weeee, look at me go!": "Weeee，看着我走！",
    "when the variable is sus! :flushed": "当变量是sus！ ：酡",
    "X marks the spot!": "X 标记位置！",
    "You know what this game needs more of? It needs more protein": "你知道这个游戏更需要什么吗？它需要更多的蛋白质",
    "'hmmm today I will dev AP' -randomtuba, 5 seconds before disaster struck": "“嗯，今天我将开发 AP”-randomtuba，灾难发生前 5 秒",
    "AP Desmos% Speedrun": "AP Desmos% Speedrun",
    "BREAKING NEWS: Algebraic Progression saves leaked across the nation by a professional hacker. Investigation is ongoing.": "突发新闻：代数级数存档被一名专业黑客泄露到全国各地。调查正在进行中。",
    "BREAKING NEWS: Famous celebrity Joe Schmirzstein says 'I can't stop dreaming about complex mathematical functions. I need help.'": "突发新闻：著名名人 Joe Schmirzstein 说：“我无法停止梦想复杂的数学函数。我需要帮助。'",
    "BREAKING NEWS: Point Portal malfunction caused 15 deaths and 3 injuries. Point Portal manager says 'we will be more careful next time'.": "突发新闻：Point Portal 故障导致 15 人死亡和 3 人受伤。 Point Portal 经理说“我们下次会更加小心”。",
    "BREAKING NEWS: We ran out of ideas": "突发新闻：我们的想法用完了",
    "Calculus do what AP don't": "微积分能做 AP 不能做的事",
    "Don't you dare divide by zero": "你敢除以零吗",
    "imagine not having spaghetti code": "想象一下没有意大利面条代码",
    "Is this a Synergism reference???????": "这是协同作用的参考吗？？？？？？",
    "It's important that the news ticker can't be disabled. The news ticker will never disappear and you will get tired of it faster.": "重要的是不能禁用新闻自动收报机。新闻自动收报机永远不会消失，你会更快厌倦它。",
    "Part 2: Tuba fucks up": "第 2 部分：大号搞砸了",
    "Pi: 'Be real for once' i: 'No, let's be rational here.'": "Pi：“真实一次” i：“不，让我们在这里保持理性。”",
    "BREAKING NEWS: Algebraic Progression saves leaked across the nation by a professional hacker. Investigation is ongoing.": "突发新闻：代数递进 存档被一名专业黑客泄露到全国各地。 调查正在进行中。",
    "imagine not having spaghetti code": "想象一下没有意大利面条代码",
    "BREAKING NEWS: Randomtuba announces removal of the Buy Max button, riots ensue.": "突发新闻：Randomtuba 宣布移除 购买最大 按钮，随后发生骚乱。",
    "Welcome to Algebraic Progression, the game where math becomes fun": "欢迎来到代数递进，让数学变得有趣的游戏",
    "'shit game remove timewalls' -reda": "'狗屎游戏删除时间墙' -reda",
    "Fun Fact: Offline time exists! You'll get a boost to production when you go back online based on how long you spend away from the game.": "有趣的事实：存在离线时间！ 当您根据您离开游戏的时间长短重新上线时，您的生产将得到提升。",
    "Fact: tuba is not a furry": "事实：tuba不是福瑞",
    "'My power grows, Gordon.' -Dr. Coomer, 2020(?": "“我的力量在增长，戈登。” -库默博士，2020（？",
    "You can't kill News Ticker Man, look at me go!": "你不能杀新闻播报员，看着我走！",
    "Here's a homework assignment for you: Prestige for 1 b": "这是给你的家庭作业： 1 b 的声望",
    "Z might be real, but W isn't": "Z 可能是真实的，但 W 不是",
    "Press Alt+F4 to die simultaneously": "按 Alt+F4 同时死亡",
    "Algebraic Progression NGUd^^^++++---- when?": "代数递进 NGUd ^^^ ++++ ---- 什么时候出来？",
    "if i see one more 5 hours joke i will fucking snap": "如果我再看到一个 5 小时的笑话，我TM会生气的",
    "BREAKING NEWS: Obamium discovered in local mine!": "突发新闻：在当地矿井中发现了 Obamium！",
    "Square Root is just Time Dilation but harder, deal with it": "平方根只是时间膨胀，但更难，处理它",
    "BREAKING NEWS: Florida Man rents Point Portal, causes hole in space-time": "突发新闻：佛罗里达男子租用 点数传送门，导致时空出现漏洞",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Current Theme: ": "当前主题：",
    "Autoclickers - ": "自动点击器 - ",
    "Function Autobuyer: ": "函数自动购买者：",
    "Building Autobuyer: ": "建筑自动购买者：",
    "Point Factories - ": "点数工厂 - ",
    "Point Portals - ": "点数传送门 - ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^购买花费 (.+)$/,
    /^您每秒获得 (.+)$/,
    /^增益 (.+)$/,
    /^(.+)\(([\d\.,]+)\) = (.+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+) ~ (.+)\/s (.+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Number = (.+)$/, '数字 = $1'],
    [/^Go Quadratic for (.+) \(Q$/, '到 $1 的二次方 \(Q'],
    [/^Buy for (.+) points \((.+)$/, '购买花费 $1 点数 \($2'],
    [/^You are getting (.+) points per second$/, '您每秒获得 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) Point$/, '$1 点数'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+)x$/, '成本：$1x'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);